In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

C:\Users\Isabel\AppData\Local\Temp\ipykernel_12388\2872363843.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df = pd.read_csv('../df_primera_limpieza.csv', index_col=0)

In [36]:
df[df['customer_type']=='Group']['children'].unique()

array([ 0., nan,  2., 14.,  1.,  3.])

In [39]:
df[(df['children']>10)&(df['customer_type']=='Transient')][['children', 'customer_type']]

children customer_type
8047        19.0     Transient
10267       17.0     Transient
11534       11.0     Transient
12812       18.0     Transient
12980       13.0     Transient
13467       17.0     Transient
13507       18.0     Transient
18310       11.0     Transient
27221       16.0     Transient
30801       14.0     Transient
32138       16.0     Transient
32262       11.0     Transient
39937       13.0     Transient
49420       12.0     Transient
50129       17.0     Transient
51624       14.0     Transient
54675       18.0     Transient
57723       13.0     Transient
60769       11.0     Transient
61040       16.0     Transient
61727       15.0     Transient
62278       18.0     Transient
68849       14.0     Transient
73445       15.0     Transient
74897       11.0     Transient
75014       15.0     Transient
82086       14.0     Transient
93009       13.0     Transient
94546       12.0     Transient
94621       14.0     Transient
97988       14.0     Transient
100287      18.0     Transient
102843      18.0     Transient
108424      15.0     Transient
112085      18.0     Transient
112761      18.0     Transient

In [31]:
df_isna = df[df['previous_cancellations'].isnull()]

df_isna

hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel        False      342.0             2015.0   
6       Resort Hotel        False        0.0             2015.0   
7       Resort Hotel        False        9.0             2015.0   
8       Resort Hotel         True       85.0             2015.0   
14      Resort Hotel        False       37.0             2015.0   
...              ...          ...        ...                ...   
119374    City Hotel        False      201.0             2017.0   
119377    City Hotel        False      185.0             2017.0   
119383    City Hotel        False      164.0             2017.0   
119384    City Hotel        False       21.0                NaN   
119386    City Hotel        False      102.0                NaN   

       arrival_date_month  arrival_date_week_number  \
0                    July                      27.0   
6                    July                       NaN   
7                    July                      27.0   
8                    July                      27.0   
14                   July                      27.0   
...                   ...                       ...   
119374             August                      35.0   
119377             August                      35.0   
119383             August                      35.0   
119384             August                       NaN   
119386             August                      35.0   

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                             1.0                      0.0   
6                             1.0                      0.0   
7                             1.0                      0.0   
8                             1.0                      0.0   
14                            1.0                      0.0   
...                           ...                      ...   
119374                       29.0                      1.0   
119377                       30.0                      1.0   
119383                       31.0                      2.0   
119384                       30.0                      2.0   
119386                       31.0                      2.0   

        stays_in_week_nights  adults  children  babies meal country  \
0                        0.0     2.0       NaN     0.0   BB     PRT   
6                        2.0     2.0       NaN     0.0   BB     NaN   
7                        2.0     2.0       0.0     0.0   FB     NaN   
8                        3.0     2.0       0.0     0.0   BB     PRT   
14                       4.0     2.0       NaN     0.0   BB     NaN   
...                      ...     ...       ...     ...  ...     ...   
119374                   5.0     2.0       NaN     0.0   BB     DEU   
119377                   4.0     2.0       0.0     0.0   SC     CHE   
119383                   4.0     2.0       0.0     0.0   BB     DEU   
119384                   5.0     2.0       0.0     0.0   BB     BEL   
119386                   5.0     3.0       NaN     0.0   BB     FRA   

       market_segment distribution_channel  is_repeated_guest  \
0                 NaN               Direct                0.0   
6              Direct               Direct                0.0   
7              Direct               Direct                0.0   
8                 NaN                  NaN                0.0   
14          Online TA                TA/TO                0.0   
...               ...                  ...                ...   
119374            NaN                TA/TO                0.0   
119377            NaN                TA/TO                0.0   
119383            NaN                TA/TO                0.0   
119384            NaN                TA/TO                0.0   
119386            NaN                TA/TO                0.0   

        previous_cancellations  previous_bookings_not_canceled  \
0                          NaN                             0.0   
6                          NaN        

In [3]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'agent', 'company',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', '0'],
      dtype='object')

In [15]:
df['arrival_date_year'].unique()

array([2015.,   nan, 2016., 2017.])

In [4]:
df1 = df.iloc[:, 9:16]
df1.dtypes

adults                  float64
children                float64
babies                  float64
meal                     object
country                  object
market_segment           object
distribution_channel     object
dtype: object

In [24]:
df['assigned_room_type'].value_counts()

assigned_room_type
A    72716
D    25280
E     7803
F     3750
G     2553
C     2374
B     2162
H      712
I      363
K      279
P       12
L        1
Name: count, dtype: int64

In [27]:
df['distribution_channel'].value_counts()

distribution_channel
TA/TO        85534
Direct       12960
Corporate     5864
GDS            176
Undefined        5
Name: count, dtype: int64

In [25]:

df['assigned_room_type'].mode()

0    A
Name: assigned_room_type, dtype: object

In [5]:
df1.isnull().sum()/df1.shape[0]*100

adults                   0.000000
children                42.052455
babies                   0.000000
meal                     0.000000
country                 45.552307
market_segment          49.798737
distribution_channel    11.411381
dtype: float64

In [12]:
df['assigned_room_type'].unique()

array(['C', 'A', 'D', 'E', 'G', 'F', 'I', 'B', 'H', 'P', 'L', 'K'],
      dtype=object)

In [13]:
df[df['children'] >0]['assigned_room_type'].unique()

array(['G', 'C', 'D', 'H', 'F', 'A', 'E', 'I', 'B', 'K'], dtype=object)

In [14]:
df[df['children'] == 0]['assigned_room_type'].unique()

array(['C', 'A', 'D', 'E', 'G', 'I', 'B', 'F', 'H', 'P', 'K'],
      dtype=object)

In [9]:
df['agent'].isnull().sum()/df.shape[0]*100

13.6858607686115

In [10]:
df['children'].unique()

array([nan,  0.,  1.,  2., 10., 19.,  3., 17., 11., 18., 13., 16., 14.,
       15., 12.])

In [11]:
df['children'].dropna().agg(['mean', 'median'])

mean      0.119887
median    0.000000
Name: children, dtype: float64

- **Sin niños** no suelen reservar L, P ('room_type')
- Hay más agentes que distribution_channel nulos

In [5]:
df = pd.read_csv('../df_primera_limpieza.csv', index_col=0)

In [42]:
df_filtrado.isnull().sum()/df_filtrado.shape[0]*100

hotel                               0.000000
is_canceled                         0.000000
lead_time                           0.000000
arrival_date_year                  45.745519
arrival_date_month                  0.000000
arrival_date_week_number           15.540019
arrival_date_day_of_month           0.100843
stays_in_weekend_nights             0.000000
stays_in_week_nights                0.000000
adults                              0.000000
children                           42.052455
babies                              0.000000
meal                                0.000000
country                            45.552307
market_segment                     49.798737
distribution_channel               11.411381
is_repeated_guest                   4.247278
previous_cancellations             36.319647
previous_bookings_not_canceled      0.000000
reserved_room_type                 33.733316
assigned_room_type                  0.000000
booking_changes                     0.000000
agent     

In [43]:
df_filtrado['customer_type'].value_counts()

customer_type
Transient          69800
Transient-Party    19406
Contract            3246
Group                460
Name: count, dtype: int64

In [ ]:
porcentaje_aparicion = df_filtrado['customer_type'].value_counts(normalize=True)

# Valores para imputar
valor1 = 'Transient'
valor2 = 'Transient-Party'

# Porcentajes de aparición de los valores
porcentaje_valor1 = porcentaje_aparicion.get(valor1, 0)
porcentaje_valor2 = porcentaje_aparicion.get(valor2, 0)

# Imputar valores nulos basados en los porcentajes
for i, valor in enumerate(df_filtrado['customer_type']):
    if pd.isnull(valor):
        # Generar un número aleatorio entre 0 y 1
        rand = np.random.rand()
        if rand < porcentaje_valor1:
            df_filtrado.loc[i, 'customer_type'] = valor1
        else:
            df_filtrado.loc[i, 'customer_type'] = valor2

display(df_filtrado)

In [49]:
df_filtrado['customer_type'].isnull().sum()/df_filtrado.shape[0]*100

16.51567649792952

In [50]:
df_filtrado['customer_type'].value_counts()

customer_type
Transient          74128
Transient-Party    21679
Contract            2625
Group                355
Name: count, dtype: int64

## COMPROBACIONES
LAURA:
- lead_time y booking_changes 
- lead_time y reservation_status
- lead_time, booking_changes  y reservation_status
>----------------
FEDRA:
- lead_time y is_cancelled 
- customer_type y is_cancelled
- assigned_room_type y is_cancelled
>----------------
NEREA:
- is_repeated_guest y is_cancelled
- is_repeated_guest y previous_cancellations, previous_bookings_not_canceled
- country y is_cancelled
>----------------
ISA:
- cuándo hay más llegadas (mes)
- cuándo se hacen más reservas (reservation_status_date)
- promedio de noches por tipo de cliente
- mapa con países que más bookean



### hilos graciosos:
- por qué repiten (is_repeated_guest y meal, etc)

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
pd.set_option('display.max_columns', None) 

In [7]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'agent', 'company',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', '0'],
      dtype='object')

In [ ]:
sns.barplot(x='                       ')